import { SetMetadata } from '@nestjs/common';

export enum Permission {
  // Admin permissions
  MANAGE_USERS = 'MANAGE_USERS',
  CONFIGURE_SYSTEM = 'CONFIGURE_SYSTEM',
  VIEW_LOGS = 'VIEW_LOGS',
  
  // Organizer permissions
  MANAGE_EVENTS = 'MANAGE_EVENTS',
  MANAGE_ATTENDEES = 'MANAGE_ATTENDEES',
  MANAGE_STAFF = 'MANAGE_STAFF',
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',
  
  // Staff permissions
  VIEW_EVENTS = 'VIEW_EVENTS',
  MANAGE_TASKS = 'MANAGE_TASKS',
  
  // Legacy permissions
  READ_PROFILE = 'READ_PROFILE',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  READ_EVENT = 'READ_EVENT',
  CREATE_EVENT = 'CREATE_EVENT',
  UPDATE_EVENT = 'UPDATE_EVENT',
  DELETE_EVENT = 'DELETE_EVENT',
  VIEW_ATTENDEES = 'VIEW_ATTENDEES',
  CHECK_IN_ATTENDEE = 'CHECK_IN_ATTENDEE',
  CREATE_SUPPORT_TICKET = 'CREATE_SUPPORT_TICKET',
  VIEW_SUPPORT_TICKETS = 'VIEW_SUPPORT_TICKETS',
  UPDATE_SUPPORT_TICKET = 'UPDATE_SUPPORT_TICKET',
  DELETE_SUPPORT_TICKET = 'DELETE_SUPPORT_TICKET',
  SEND_NOTIFICATIONS = 'SEND_NOTIFICATIONS',
  VIEW_REPORTS = 'VIEW_REPORTS',
}

export const PERMISSIONS_KEY = 'permissions';
export const Permissions = (...permissions: Permission[]) => SetMetadata(PERMISSIONS_KEY, permissions); 